// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TRIO2026.Data.Contexts;

#nullable disable

namespace TRIO2026.Data.Migrations.Main
{
    [DbContext(typeof(MainDbContext))]
    partial class MainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("TRIO2026.Core.Entities.FlowDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlowName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("ModifiedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("SampleType")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalSteps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlowName")
                        .IsUnique();

                    b.ToTable("FlowDefinition", (string)null);
                });

            modelBuilder.Entity("TRIO2026.Core.Entities.FlowMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BuiltInFlowName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsumableLayoutCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ElutionVolume")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExtractionTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FlowCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LoadingVolume")
                        .HasColumnType("TEXT");

                    b.Property<string>("SampleType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlowCode")
                        .IsUnique();

                    b.ToTable("FlowMapping", (string)null);
                });

            modelBuilder.Entity("TRIO2026.Core.Entities.FlowStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Arg0")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double>("Arg1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double>("Arg2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double>("Arg3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double>("Arg4")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<int>("CommandId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Crc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("FlowDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupDepth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT");

                    b.Property<int>("StepOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StringArg")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlowDefinitionId", "StepOrder");

                    b.ToTable("FlowStep", (string)null);
                });

            modelBuilder.Entity("TRIO2026.Core.Entities.PnidMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionZh")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedProductCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("PnidCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PnidCode")
                        .IsUnique();

                    b.ToTable("PnidMapping", (string)null);
                });

            modelBuilder.Entity("TRIO2026.Core.Entities.RoleDefinition", b =>
                {
                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Level");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("RoleDefinition", (string)null);
                });

            modelBuilder.Entity("TRIO2026.Core.Entities.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("AvatarImage")
                        .HasColumnType("BLOB");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLoginCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LockedUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleLevel");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UserAccount", (string)null);
                });

            modelBuilder.Entity("TRIO2026.Core.Entities.FlowStep", b =>
                {
                    b.HasOne("TRIO2026.Core.Entities.FlowDefinition", "FlowDefinition")
                        .WithMany("Steps")
                        .HasForeignKey("FlowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlowDefinition");
                });

            modelBuilder.Entity("TRIO2026.Core.Entities.UserAccount", b =>
                {
                    b.HasOne("TRIO2026.Core.Entities.RoleDefinition", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleLevel")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TRIO2026.Core.Entities.FlowDefinition", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("TRIO2026.Core.Entities.RoleDefinition", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
