// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TRIO2026.Data.Contexts;

#nullable disable

namespace TRIO2026.Data.Migrations.Config
{
    [DbContext(typeof(ConfigDbContext))]
    [Migration("20260430033029_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("TRIO2026.Core.Entities.CommandDefinition", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Arg0Label")
                        .HasColumnType("TEXT");

                    b.Property<string>("Arg0Options")
                        .HasColumnType("TEXT");

                    b.Property<int>("Arg0Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Arg1Label")
                        .HasColumnType("TEXT");

                    b.Property<string>("Arg1Options")
                        .HasColumnType("TEXT");

                    b.Property<int>("Arg1Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Arg2Label")
                        .HasColumnType("TEXT");

                    b.Property<string>("Arg2Options")
                        .HasColumnType("TEXT");

                    b.Property<int>("Arg2Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Arg3Label")
                        .HasColumnType("TEXT");

                    b.Property<string>("Arg3Options")
                        .HasColumnType("TEXT");

                    b.Property<int>("Arg3Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Arg4Label")
                        .HasColumnType("TEXT");

                    b.Property<string>("Arg4Options")
                        .HasColumnType("TEXT");

                    b.Property<int>("Arg4Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("DisplayFormat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CommandDefinition", (string)null);
                });

            modelBuilder.Entity("TRIO2026.Core.Entities.SystemConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("string");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Key")
                        .IsUnique();

                    b.ToTable("SystemConfig", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
